[package]
name = "aoc2024"
version = "0.1.0"
edition = "2024"

[dependencies]
itertools = "0.14"
owo-colors = "4"
paste = "1.0"
rayon = "1.11"
regex = "1.12"
stopwatch = "0.0.7"

[dev-dependencies]
test-case = "3.3"
